Hospital App/hospital_management/urls.py
from django.contrib import admin
from django.urls import path, include
from login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', views.register, name = 'register'),
    path('', include('main_site.urls')),
]

Hospital App/main_site/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as defaultViews

urlpatterns = [
    path('', views.homepage, name = 'homepage'),
    path('account/login/', defaultViews.LoginView.as_view(), name='login'),
    path('account/logout/', defaultViews.LogoutView.as_view(next_page='/'), name='logout'),
    path('add/patient/', views.add_patient, name='add_patient'),
    path('rooms/', views.rooms, name='rooms'),
    path('blankets/', views.blankets, name='blankets'),
    path('appointments/', views.appointments, name='appointments'),
    path('payments/', views.process_payments, name='payments'),
    path('doctors/', views.show_doctors, name='show_doctors'),
    path('nurses/', views.show_nurses, name='show_nurses'),
    path('profiles/<int:pk>', views.profiles, name='profiles'),
    path('ajax/load-doctors/', views.load_doctors, name='ajax_load_doctors'),
    path('ajax/load-days/', views.load_days, name='ajax_load_days'),
    path('ajax/load-paymnet/', views.load_payment, name='ajax_load_payment'),
    path('appointments/view/', views.show_appointments, name='show_appointments'),
    path('appointments/delete/<int:pk>', views.delete_appointment, name='delete_appointment'),
    path('hospitalizations/view/', views.show_hospitlizations, name='show_hospitlizations'),
    path('hospitalizations/delete/<int:pk>', views.delete_hospitlization, name='delete_hospitlization'),
]

Hospital App/main_site/models.py
from django.db import models
from django.db.models.fields import DateField
from django.db.models.fields.related import ForeignKey
from login.models import User
import datetime

class Patient(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    identifier = models.CharField(max_length=20)
    sex = models.CharField(max_length=20)
    blood_type = models.CharField(max_length=20)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class Date(models.Model):
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class Appointment(models.Model):
    treatment_type = models.CharField(max_length=20)
    doctor = models.ForeignKey(User, on_delete=models.CASCADE)
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE)
    date = models.ForeignKey(Date, on_delete=models.CASCADE, null=True)

class Room(models.Model):
    number = models.IntegerField()
    bed = models.IntegerField()

    def __str__(self):
        return str(self.number)

class Hospitalization(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    occupied_bed = models.IntegerField(null=True)
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE)
    admission_date = models.DateField(null=True)

Hospital App/main_site/forms.py
from django import forms
from .models import Patient, Appointment, Room, Hospitalization
from login.models import User

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('first_name', 'last_name', 'identifier', 'sex', 'blood_type')

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ('treatment_type', 'doctor', 'patient', 'date')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['doctor'].queryset = User.objects.none()

        if 'treatment_type' in self.data:
            try:
                treatment = self.data.get('treatment_type')
                self.fields['doctor'].queryset = User.objects.filter(job = 'Doctor').filter(specializare = treatment)
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['doctor'].queryset = self.instance.treatment.doctor_set.order_by('name')

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ('treatment_type', 'doctor', 'patient', 'date')

class HospitalizationForm(forms.ModelForm):
    class Meta:
        model = Hospitalization
        fields = ('room', 'patient')

Hospital App/main_site/views.py
from typing import _SpecialForm
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from .forms import PatientForm, AppointmentForm, HospitalizationForm
from login.models import User
from .models import Patient, Date, Appointment, Room, Hospitalization
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
import datetime


@login_required(login_url='/account/login/')
def homepage(request):
    return render(request, 'site/index.html', {})

@login_required(login_url='/account/login/')
def profile_page(request):
    current_user = request.user
    return render(request, 'site/profile.html', {'current_user': current_user})

@login_required(login_url='/account/login/')
def profiles(request, pk):
    profile = User.objects.get(pk = pk)
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('homepage')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'site/profile.html', {'current_user': profile, 'form': form})

@login_required(login_url='/account/login/')
def add_patient(request):
    if request.method == "POST":
        form = PatientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage')
    else:
        form = PatientForm()
    return render(request, 'site/adauga_pacient.html', {'form': form})

@login_required(login_url='/account/login/')
def blankets(request):
    return render(request, 'site/paturi.html', {})

@login_required(login_url='/account/login/')
def appointments(request):
    treatments = User.objects.filter(job = 'Doctor').order_by('specializare').values_list('specializare').distinct()
    date = Date.objects.all()
    patients = Patient.objects.all()
    noAppointmentPatients = []
    
    for patient in patients:
        try:
            if (patient.appointment):
                pass
        except:
                noAppointmentPatients.append(patient)

    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('show_appointments')
    else:
        form = AppointmentForm()
    return render(request, 'site/programari.html', {'form': form, 'treatments': treatments, 'patients': noAppointmentPatients, 'dates': date})

@login_required(login_url='/account/login/')
def show_doctors(request):
    doctors = User.objects.filter(job = 'Doctor')
    return render(request, 'site/afiseaza_job.html', {'jobs': doctors, 'title': 'Doctori'})

@login_required(login_url='/account/login/')
def show_nurses(request):
    nurses = User.objects.filter(job = 'Asistenta')
    return render(request, 'site/afiseaza_job.html', {'jobs': nurses, 'title': 'Asistente'})

@login_required(login_url='/account/login/')
def show_appointments(request):
    appointments = Appointment.objects.all()
    return render (request, 'site/afiseaza_programari.html', {'appointments': appointments})

@login_required(login_url='/account/login/')
def delete_appointment(request, pk):
    appointment = Appointment.objects.get(pk = pk)
    if request.method == 'POST':
        appointment.delete()
        return redirect('show_appointments')

@login_required(login_url='/account/login/')
def load_doctors(request):
    treatment = request.GET.get('treatment_type')
    doctors = User.objects.filter(job = 'Doctor').filter(specializare = treatment)
    return render(request, 'dynamic/dropdown_list_options.html', {'doctors': doctors})

@login_required(login_url='/account/login/')
def load_days(request):
    patient = request.GET.get('patient')
    hospitalization_day = Patient.objects.filter(identifier = patient)[0].hospitalization.admission_date
    days = (datetime.date.today() - hospitalization_day).days
    return render(request, 'dynamic/load_days.html', {'days': days})

@login_required(login_url='/account/login/')
def load_payment(request):
    days = str(request.GET.get('days'))
    payment = 500 * int(days)
    return render(request, 'dynamic/load_payment.html', {'payment': payment})

@login_required(login_url='/account/login/')
def rooms(request):
    rooms = Room.objects.filter(bed = 1)
    patients = Patient.objects.all()
    noRoomPatients = []
    
    for patient in patients:
        try:
            if (patient.hospitalization):
                pass
        except:
                noRoomPatients.append(patient)

    noRoom = []
    hospitalizations = Hospitalization.objects.all()
    for room in rooms:
        flag = False
        for hospitalization in hospitalizations:
            if (room == hospitalization.room):
                flag = True
                break
        if (flag == False):
            noRoom.append(room)

    if request.method == 'POST':
        form = HospitalizationForm(request.POST)
        if form.is_valid():
            room = form.save(commit=False)
            room.admission_date = datetime.date.today()
            room.occupied_bed = 1
            room.save()
            return redirect('homepage')
    else:
        form = HospitalizationForm()
    return render(request, 'site/camere.html', {'form': form, 'rooms': noRoom, 'patients': noRoomPatients})

@login_required(login_url='/account/login/')
def show_hospitlizations(request):
    hospitalizations = Hospitalization.objects.all()
    return render (request, 'site/afiseaza_internari.html', {'hospitalizations': hospitalizations})

@login_required(login_url='/account/login/')
def delete_hospitlization(request, pk):
    hospitalization = Hospitalization.objects.get(pk = pk)
    if request.method == 'POST':
        hospitalization.delete()
        return redirect('show_hospitlizations')

@login_required(login_url='/account/login/')
def process_payments(request):
    patients = Patient.objects.all()
    hospitalizationPatients = []
    
    for patient in patients:
        try:
            if (patient.hospitalization):
                hospitalizationPatients.append(patient)
        except:
            pass
    
    return render (request, 'site/plati.html', {'patients': hospitalizationPatients})

Hospital App/main_site/templates/site/adauga_pacient.html
{% extends "site/index.html" %}

{% block content %}
<div id="main-content" class="section">
    <div class="box2">
        <form method="post" action="{% url 'add_patient' %}">
            {% csrf_token %}
            <h1>Adauga pacienti</h1>
            <hr>
            <h2 for="id_first_name">Nume</h2>
            <input id="id_first_name" type="text" name="first_name" required>
            <h2 for="id_last_name">Prenume</h2>
            <input id="id_last_name" type="text" name="last_name" required>
            <h2 for="id_identifier">C.N.P.</h2>
            <input id="id_identifier" type="text" name="identifier" required>
            <h2 for="id_sex">Sex</h2>
            <select id="id_sex" name="sex" required>
                <option value="" selected disabled hidden>Alege sex-ul</option>
                <option value="Masculin">Masculin</option>
                <option value="Feminin">Feminin</option>
            </select>
            <h2 for="id_blood_type">Grupa sanguina</h2>
            <select id="id_blood_type" name="blood_type" required>
                <option value="" selected disabled hidden>Alege grupa sanguina</option>
                <option value="O+">O+</option>
                <option value="O-">O-</option>
                <option value="A+">A+</option>
                <option value="A-">A-</option>
                <option value="B+">B+</option>
                <option value="B-">B-</option>
                <option value="AB+">AB+</option>
                <option value="AB-">AB-</option>
            </select>
            <br><br>
            <button type="submit">Adauga</button>
            <button onclick = "location.href = '/'; ">Anuleaza</button>
        </form>
    </div>
</div>
{% endblock %}

Hospital App/main_site/templates/site/afiseaza_internari.html
{% extends "site/index.html" %}

{% block content %}
<div id="main-content" class="section">
    <div class="box2">
        <h1>Internari</h1>
        <hr>
        <table class = "appointment">
            <tr>
                <th>Camera</th>
                <th>Pacient</th>
                <th>Data internarii</th>
                <th>Pat</th>
            </tr>
            {% for hospitalization in hospitalizations %}
                <tr>
                    <td>{{ hospitalization.room }}</td>
                    <td>{{ hospitalization.patient }}</td>
                    <td>{{ hospitalization.admission_date }}</td>
                    <td>{{ hospitalization.occupied_bed }}</td>
                    <td>
                        <form method = "post" action="{% url 'delete_hospitlization' pk=hospitalization.pk%}">
                            {% csrf_token %}
                            <input type="submit" value='Sterge' class="btn btn-warning">
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

Hospital App/main_site/templates/site/afiseaza_job.html
{% extends "site/index.html" %}

{% block content %}
<div id="main-content" class="section">
    <div class="box2">
        <h1>{{ title }}</h1>
        <hr>
        {% for job in jobs %}
            <div>
                <p><a href="{% url 'profiles' pk=job.pk %}">{{ job.username|linebreaksbr }}</a></p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Hospital App/main_site/templates/site/afiseaza_programari.html
{% extends "site/index.html" %}

{% block content %}
<div id="main-content" class="section">
    <div class="box2">
        <h1>Programari</h1>
        <hr>
        <table class = "appointment">
            <tr>
                <th>Specializare</th>
                <th>Doctor</th>
                <th>Pactient</th>
                <th>Data</th>
            </tr>
            {% for appointment in appointments %}
                <tr>
                    <td>{{ appointment.treatment_type }}</td>
                    <td>{{ appointment.doctor }}</td>
                    <td>{{ appointment.patient }}</td>
                    <td>{{ appointment.date }}</td>
                    <td>
                        <form method = "post" action="{% url 'delete_appointment' pk=appointment.pk%}">
                            {% csrf_token %}
                            <input type="submit" value='Sterge' class="btn btn-warning">
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

Hospital App/main_site/templates/site/camere.html
{% extends "site/index.html" %}

{% block content %}
<div id="main-content" class="section">
    <div class="box2">
        <form method="post" action="{% url 'rooms' %}">
            {% csrf_token %}
            <h1>Camere</h1>
            <hr>
            <h2 for="id_room">Numarul camerei</h2>
            <select id="id_room" name="room" required>
                <option value="" selected disabled hidden>Alege camera</option>
                {% for room in rooms %}
                    <option value="{{ room.pk }}">{{ room }}</option>
                {% endfor %}
            </select>
            <h2 for="id_patient">Pacient</h2>
            <select id="id_patient" name="patient" required>
                <option value="" selected disabled hidden>Alege pacientul</option>
                {% for patient in patients %}
                    <option value="{{ patient.pk }}">{{ patient }}</option>
                {% endfor %}
            </select>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %} 
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
            {% endif %}
            <br><br>
            <button type="submit">Interneaza</button>
            <button onclick = "location.href = '/'; ">Anuleaza</button>
            <button onclick = "location.href = 'http://127.0.0.1:8000/hospitalizations/view/'; ">Lista pacineti internati</button>
        </form>
    </div>
</div>
{% endblock %}

Hospital App/main_site/templates/site/index.html
{% load static %}
<html>
<head>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet" />
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<title>Hospital Management System</title>
</head>
<body>
{% if user.is_authenticated %}
<header id="site-header" class="section">
		<div class="container">
			<div class="main-navigation">
				<nav>
					<ul>
						<li><a href="/">Acasa</a></li>
						<li><a href="{% url 'rooms' %}">Camere</a></li>
						<li class="dropdown">
							<a href="javascript:void(0)" class="dropbtn">Pacienti</a>
							<div class="dropdown-content">
								<a href="{% url 'add_patient' %}">Adauga</a>
								<a href="{% url 'appointments' %}">Programari</a>
								<a href="{% url 'payments' %}">Plati</a>
							</div>
						</li>
						<li class="dropdown">
							<a href="javascript:void(0)" class="dropbtn">Utilizatori</a>
							<div class="dropdown-content">
								{% if user.is_superuser %}
									<a href="{% url 'register' %}">Adauga</a>
								{% endif %}
								<a href="{% url 'show_doctors' %}">Doctori</a>
								<a href="{% url 'show_nurses' %}">Asistente</a>
							</div>
						</li>
						<li>
							<a href = "{% url 'profiles' pk=user.pk %}">Profil</a></li>
						<li>
							<a href = "{% url 'logout' %}"><button>Log out</button></a>
						</li>
					</ul>
				</nav>
			</div>
		</div>
</header>
{% endif %}
{% block content %}
{% endblock %}
</body>
</html>

Hospital App/main_site/templates/site/paturi.html
{% extends "site/index.html" %}

{% block content %}
<div id="main-content" class="section">
    <div class="box2">
        <form>
            <h1>Paturi</h1>
            <hr>
            <h2>Numarul camerei</h2>
            <input type="text" name="Numarul camerei">
            <h2>ID pacient</h2>
            <input type="text" name="ID Pacient">
            <h2>Numarul patului</h2>
            <input type="text" name="Numarul patului">
            <h2>Data internarii</h2>
            <input type="text" name="Data internarii">
        </form>
        <br>
        <button>Interneaza</button>
        <button onclick = "location.href = '/'; ">Anuleaza</button>
        <button>Lista pacineti internati</button>
    </div>
</div>
{% endblock %}

Hospital App/main_site/templates/site/plati.html
{% extends "site/index.html" %}

{% block content %}
<div id="main-content" class="section">
    <div class="box2">
        <form>
            <h1>Plati</h1>
            <hr>
            <h2>Pacient</h2>
            <select id="id_patient" name="patient"required>
                <option value="" selected disabled hidden>Alege pacient</option>
                {% for patient in patients %}
                    <option value="{{ patient.identifier }}">{{ patient }}</option>
                {% endfor %}
            </select>
            <h2>Internare- numar zile</h2>
            <div id="id_number_of_days"></div>
            <h2>Metoda de plata</h2>
            <select id="payment_method" required>
                <option value="" selected disabled hidden>Alege metoda de plata</option>
                <option value="Card">Card</option>
                <option value="Cash">Cash</option>
            </select>
            <h2>Total de plata</h2>
            <div id="id_payment"></div>
        </form>
        <br>
        <button onclick = "location.href = '/'; ">Plateste</button>
        <button onclick = "location.href = '/'; ">Anuleaza</button>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script>
            $("#payment_method").change(function () {
              var url = "{% url 'ajax_load_payment' %}";
              var days = $("#payment_days").val();
  
              $.ajax({
                url: url,
                data: {
                  'days': days
                },
                success: function (data) {
                  $("#id_payment").html(data);
                }
              });
            });
        </script>

        <script>
          $("#id_patient").change(function () {
            var url = "{% url 'ajax_load_days' %}";
            var patient = $(this).val();
      
            $.ajax({
              url: url,
              data: {
                'patient': patient
              },
              success: function (data) {
                $("#id_number_of_days").html(data);
              }
            });
          });
        </script>
    </div>
</div>
{% endblock %}

Hospital App/main_site/templates/site/profile.html
{% extends "site/index.html" %}

{% block content %}
<div id="main-content" class="section">
    <div class="box2">
        <form method="post" action="{% url 'profiles' pk=current_user.pk%}">
            {% csrf_token %}
            <h1>Profil</h1>
            <hr>
            <h2>Nume utilizator</h2>
            <p>{{current_user.username}}</p>
            <h2>Email</h2>
            <p>{{current_user.email}}</p>
            <h2>ID</h2>
            {% if current_user.is_superuser %}
                <p>Admin {{current_user.id}}</p>
            {% else %}
                <p>{{current_user.id}}</p>
            {% endif %}
            <h2>Job</h2>
            <p>{{current_user.job}}</p>
            <h2>Grupa sanguina</h2>
            <p>{{current_user.grupa_sanguina}}</p>
            {% if user.is_superuser or user == current_user %}
                <h2>Schimba Parola</h2>
                <div class="form-group">
                    <label for="{{ form.id_old_password }}">Parola Veche</label>
                    {{ form.old_password }}
                </div>
                <div class="form-group">
                    <label for="{{ form.id_new_password1 }}">Parola Noua</label>
                    {{ form.new_password1 }}
                </div>
                <div class="form-group">
                    <label for="{{ form.id_new_password2 }}">Repeta parola noua</label>
                    {{ form.new_password2 }}
                </div>
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %} 
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
                <button type="submit">Salveaza</button>
            {% endif %}
        </form>
        <button onclick = "location.href = '/'; ">Anuleaza</button>
    </div>
</div>
{% endblock %}

Hospital App/main_site/templates/site/programari.html
{% extends "site/index.html" %}

{% block content %}
<div id="main-content" class="section">
    <div class="box2">
        <form method="post" id="appointmentForm" data-doctors-url="{% url 'ajax_load_doctors' %}">
            {% csrf_token %}
            <h1>Programari</h1>
            <hr>
            <h2 for="id_treatment_type" >Specializare</h2>
            <select id="id_treatment_type" name="treatment_type" required>
                <option value="" selected disabled hidden>Alege specializarea</option>
                {% for treatment in treatments %}
                    {% for specializare in treatment %}
                        <option value="{{ specializare }}">{{ specializare }}</option>
                    {% endfor %}
                {% endfor %}
            </select>
            <h2 for="id_doctor">Doctor</h2>
            {{ form.doctor }}
            <h2 for="id_date">Data</h2>
            <select id="id_date" name="date" required>
              <option value="" selected disabled hidden>Alege data</option>
              {% for date in dates %}
                  <option value="{{ date.pk }}">{{ date }}</option>
              {% endfor %}
            </select>
            <h2 for="id_patient">Pacient</h2>
            <select id="id_patient" name="patient" required>
              <option value="" selected disabled hidden>Alege pacientul</option>
              {% for patient in patients %}
                    <option value="{{ patient.pk }}">{{ patient }}</option>
              {% endfor %}
            </select>
            <br><br>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %} 
                    <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                    </div>
                    <br>
                    {% endfor %}
                {% endfor %}
            {% endif %}
            <button type="submit">Adauga</button>
            <button onclick = "location.href = '/'; ">Anuleaza</button>
            <button onclick = "location.href = 'http://127.0.0.1:8000/appointments/view/'; ">Lista programari</button>
        </form>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script>
          $("#id_treatment_type").change(function () {
            var url = $("#appointmentForm").attr("data-doctors-url");
            var treatment = $(this).val();
      
            $.ajax({
              url: url,
              data: {
                'treatment_type': treatment
              },
              success: function (data) {
                $("#id_doctor").html(data);
              }
            });
          });
        </script>
    </div>
</div>
{% endblock %}