Hospital App/hospital_management/urls.py
from django.contrib import admin
from django.urls import path, include
from login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', views.register, name = 'register'),
    path('', include('main_site.urls')),
]

Hospital App/main_site/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as defaultViews

urlpatterns = [
    path('', views.homepage, name = 'homepage'),
    path('account/login/', defaultViews.LoginView.as_view(), name='login'),
    path('account/logout/', defaultViews.LogoutView.as_view(next_page='/'), name='logout'),
    path('add/patient/', views.add_patient, name='add_patient'),
    path('rooms/', views.rooms, name='rooms'),
    path('blankets/', views.blankets, name='blankets'),
    path('appointments/', views.appointments, name='appointments'),
    path('payments/', views.process_payments, name='payments'),
    path('doctors/', views.show_doctors, name='show_doctors'),
    path('nurses/', views.show_nurses, name='show_nurses'),
    path('profiles/<int:pk>', views.profiles, name='profiles'),
    path('ajax/load-doctors/', views.load_doctors, name='ajax_load_doctors'),
    path('ajax/load-days/', views.load_days, name='ajax_load_days'),
    path('ajax/load-paymnet/', views.load_payment, name='ajax_load_payment'),
    path('appointments/view/', views.show_appointments, name='show_appointments'),
    path('appointments/delete/<int:pk>', views.delete_appointment, name='delete_appointment'),
    path('hospitalizations/view/', views.show_hospitlizations, name='show_hospitlizations'),
    path('hospitalizations/delete/<int:pk>', views.delete_hospitlization, name='delete_hospitlization'),
]

Hospital App/login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    specializare = models.CharField(blank=True, max_length=120)
    grupa_sanguina = models.CharField(blank=True, max_length = 20)
    job = models.CharField(blank=True, max_length = 20)

Hospital App/main_site/models.py
from django.db import models
from django.db.models.fields import DateField
from django.db.models.fields.related import ForeignKey
from login.models import User
import datetime

class Patient(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    identifier = models.CharField(max_length=20)
    sex = models.CharField(max_length=20)
    blood_type = models.CharField(max_length=20)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class Date(models.Model):
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class Appointment(models.Model):
    treatment_type = models.CharField(max_length=20)
    doctor = models.ForeignKey(User, on_delete=models.CASCADE)
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE)
    date = models.ForeignKey(Date, on_delete=models.CASCADE, null=True)

class Room(models.Model):
    number = models.IntegerField()
    bed = models.IntegerField()

    def __str__(self):
        return str(self.number)

class Hospitalization(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    occupied_bed = models.IntegerField(null=True)
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE)
    admission_date = models.DateField(null=True)

Hospital App/login/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username','email', 'password1', 'password2', 'specializare', 'grupa_sanguina', 'job')

    def clean_email(self):
            email = self.cleaned_data.get('email')

            try:
                User.objects.get(email=email)
            except User.DoesNotExist:
                return email

            raise forms.ValidationError(('Aceasta adresa de email este deja folosita!'), code = 'invalid')

Hospital App/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm

@login_required(login_url='/account/login/')
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = RegisterForm()
    return render(request, "register/register.html", {"form":form})

Hospital App/login/templates/register/register.html
{% extends "site/index.html" %}

{% block content %}
    <div id="main-content" class="section">
        <div class="box2">
            <form method="post" action="{% url 'register' %}">
                {% csrf_token %}
                <h1>Adauga utilizator</h1>
                <hr>
                <h2 for="id_username">Nume utilizator</h2>
                <input id="id_username" type="text" name="username" required>
                <h2 for="id_email">Email</h2>
                <input id="id_email" type="email" name="email" required>
                <h2 for="id_identifier">Specializare</h2>
                <input id="id_identifier" type="text" name="identifier" required>
                <h2 for="id_job">Job</h2>
                <select id="id_job" name="job" required>
                    <option value="" selected disabled hidden>Alege job-ul</option>
                    <option value="Doctor">Doctor</option>
                    <option value="Asistenta">Asistenta</option>
                </select>
                <h2 for="id_grupa_sanguina">Grupa sanguina</h2>
                <select id="id_grupa_sanguina" name="grupa_sanguina" required>
                    <option value="" selected disabled hidden>Alege grupa sanguina</option>
                    <option value="O+">O+</option>
                    <option value="O-">O-</option>
                    <option value="A+">A+</option>
                    <option value="A-">A-</option>
                    <option value="B+">B+</option>
                    <option value="B-">B-</option>
                    <option value="AB+">AB+</option>
                    <option value="AB-">AB-</option>
                </select>
                <h2 for="id_password1">Parola</h2>
                <input id="id_password1" name="password1" type="password" required>
                <h2 for="id_password2">Repeta parola</h2>
                <input id="id_password2" name="password2" type="password" required>
                <br><br>
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %} 
                        <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                        </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
                <br>
                <button type="submit">Adauga</button>
                <button onclick = "location.href = '/'; ">Anuleaza</button>
            </form>
        </div>
    </div>
{% endblock %}